[package]
name = "olmmcc"
version = "0.1.0"
authors = ["Justus Croskery <justus@olmmcc.tk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "16.0.2"
threadpool = "1.7.1"
serde_json = "1.0.40"
serde = { version = "1.0.97", features = ["derive"] }
