[package]
name = "olmmcc"
version = "0.1.0"
authors = ["Justus Croskery <justus@olmmcc.tk>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "16.1.0"
threadpool = "1.7.1"
serde_json = "1.0.41"
htmlescape = "0.3.1"
chrono = "0.4.9"
scrypt = "0.2.0"
email-format = "0.7.0"
session = { git = "https://github.com/Somebody62/session" }
http = { git = "https://github.com/Somebody62/http" }

[dependencies.serde]
version = "1.0.101"
default-features = false
features = ["derive"]
