[package]
name = "olmmcc"
version = "0.1.0"
authors = ["Justus Croskery <justus@olmmcc.tk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "16.0.2"
threadpool = "1.7.1"
serde_json = "1.0.40"
htmlescape = "0.3.1"
chrono = "0.4.7"
mysql_common = "0.17.1"
scrypt = "0.2.0"

[dependencies.serde]
version = "1.0.98"
default-features = false
features = ["derive"]
